In [24]:
import pandas as pd

In [25]:
histories = !ls *.csv

In [26]:
histories

['Hypercube_8_2_1_1.csv',
 'Hypercube_8_2_2_1.csv',
 'Hypercube_8_2_2_2.csv',
 'Hypercube_8_2_2_3.csv',
 'Hypercube_8_2_2_4.csv',
 'Hypercube_8_2_2_6.csv',
 'Hypercube_8_2_2_8.csv',
 'Hypercube_8_2_4_3.csv',
 'Hypercube_8_2_4_4.csv',
 'Hypercube_8_2_4_5.csv',
 'Hypercube_8_2_4_6.csv',
 'Hypercube_8_2_4_7.csv',
 'Hypercube_8_2_4_8.csv',
 'Hypercube_8_2_6_1.csv',
 'Hypercube_8_2_6_2.csv',
 'Hypercube_8_2_6_4.csv',
 'Hypercube_8_2_6_5.csv',
 'Hypercube_8_2_6_7.csv',
 'Hypercube_8_2_6_8.csv',
 'Hypercube_8_2_8_1.csv',
 'Hypercube_8_2_8_2.csv',
 'Hypercube_8_2_8_3.csv',
 'Hypercube_8_2_8_4.csv',
 'Hypercube_8_2_8_5.csv',
 'Hypercube_8_2_8_6.csv',
 'Hypercube_8_2_8_7.csv',
 'Hypercube_8_2_8_8.csv']

In [27]:
def get_min_col(df, colname):
    return pd.to_numeric(df[colname], errors="coerce").dropna().min()

In [47]:
names = ["keypoints", "depth", "lattices", "loss", "val_loss"]
results = {n : [] for n in names}
for history in histories:
    df = pd.read_csv(history, delimiter=";")
    _, keypoints, _, lattices, depth = history[:-4].split("_")
    results["keypoints"].append(int(keypoints))
    results["depth"].append(int(depth))
    results["lattices"].append(int(lattices))
    results["loss"].append(get_min_col(df, "loss"))
    results["val_loss"].append(get_min_col(df, "val_loss"))
result_df = pd.DataFrame.from_dict(results)

In [51]:
print(result_df.to_csv())

,keypoints,depth,lattices,loss,val_loss
0,8,1,1,12.735994234200447,12.713913193734626
1,8,1,2,12.099271515023885,11.439809482571535
2,8,2,2,13.408696093956248,12.076111918014222
3,8,3,2,13.291877799641805,12.223272201334558
4,8,4,2,13.811248661818382,11.751397192995613
5,8,6,2,11.953003540260664,11.972024712016301
6,8,8,2,18.87603308000619,11.451794343762634
7,8,3,4,11.558598965487572,11.568475166824618
8,8,4,4,12.772418670756144,10.123329048213431
9,8,5,4,12.879575682253918,10.24519874122176
10,8,6,4,15.16491633624547,12.041470641170385
11,8,7,4,9.931200931776276,9.938714612057572
12,8,8,4,16.654729182188795,11.87613281519127
13,8,1,6,11.923744130150206,11.250423514108697
14,8,2,6,11.626504847009265,11.114973546559725
15,8,4,6,14.25472940491768,11.853101531768026
16,8,5,6,12.474264646907748,10.624664211780717
17,8,7,6,5.0863931519828895,5.088336294628603
18,8,8,6,17.196241492828324,10.462355828601684
19,8,1,8,12.034450990268539,11.296294693157744
20,8,2,8,10.560171339631935,9.080628676684707
21,8,3,8,7.045444062218249,7.010826034252172
22,8,4,8,13.356621699960193,11.719801802584431
23,8,5,8,5.501005490664864,5.379641886998961
24,8,6,8,5.0168444327250645,4.903182068678467
25,8,7,8,13.657139376847827,9.674566076546876
26,8,8,8,14.766134284315198,12.58331273794258

In [50]:
result_df.sort_values("val_loss")

    keypoints  depth  lattices       loss   val_loss
24          8      6         8   5.016844   4.903182
17          8      7         6   5.086393   5.088336
23          8      5         8   5.501005   5.379642
21          8      3         8   7.045444   7.010826
20          8      2         8  10.560171   9.080629
25          8      7         8  13.657139   9.674566
11          8      7         4   9.931201   9.938715
8           8      4         4  12.772419  10.123329
9           8      5         4  12.879576  10.245199
18          8      8         6  17.196241  10.462356
16          8      5         6  12.474265  10.624664
14          8      2         6  11.626505  11.114974
13          8      1         6  11.923744  11.250424
19          8      1         8  12.034451  11.296295
1           8      1         2  12.099272  11.439809
6           8      8         2  18.876033  11.451794
7           8      3         4  11.558599  11.568475
22          8      4         8  13.356622  11.719802
4           8      4         2  13.811249  11.751397
15          8      4         6  14.254729  11.853102
12          8      8         4  16.654729  11.876133
5           8      6         2  11.953004  11.972025
10          8      6         4  15.164916  12.041471
2           8      2         2  13.408696  12.076112
3           8      3         2  13.291878  12.223272
26          8      8         8  14.766134  12.583313
0           8      1         1  12.735994  12.713913